name: Test this fuckass bullshit

on: [ push ]

jobs:
    test:
        runs-on: ubuntu-latest
        name: fuckass test
        steps:
          - name: checkout the code into the workspace runner (copy code to vm running the automation)
            uses: actions/checkout@v4
          - name: install fucking python
            uses: actions/setup-python@v5
          - name: install flake8
            run: pip install flake8
          - name: check the code
            run: flake8 main.py
    delivery:
        runs-on: ubuntu-latest
        # make sure that test is complete use needs
        needs: test
        name: fucking build the dockerfile
        steps:
          - name: checkout the code ofc
            uses: actions/checkout@v4
          - name: login into docker hub
            uses: docker/login-action@v3
            with:
              username: $({secrets.DOCKERHUB_USERNAME})
              password: $({secrets.DOCKERHUB_PASSWORD})
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: devopspython:latest